import Product from "./models/Product.js";

const menu = [
  // 1. Beverages
  {
    name: "Masala Chai",
    description: "Traditional Indian milk tea brewed with aromatic spices like cardamom, ginger, and cloves.",
    price: 60.0,
    category: "Beverages",
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800&q=80",
  },
  {
    name: "Sweet Lassi",
    description: "Creamy, chilled yogurt drink blended with sugar, a hint of cardamom, and topped with saffron.",
    price: 140.0,
    category: "Beverages",
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1626132647523-66f5bf380027?w=800&q=80",
  },
  {
    name: "Cold Coffee",
    description: "Smooth, rich blended iced coffee with milk, vanilla ice cream, and chocolate syrup.",
    price: 180.0,
    category: "Beverages",
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=800&q=80",
  },
  {
    name: "Fresh Lime Soda",
    description: "Refreshing carbonated lime juice served with your choice of sweet, salted, or mixed.",
    price: 120.0,
    category: "Beverages",
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&q=80",
  },
  {
    name: "Mango Shake",
    description: "Thick and luscious shake made with fresh seasonal mango pulp, whole milk, and dry fruits.",
    price: 180.0,
    category: "Beverages",
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=800&q=80",
  },
  {
    name: "Badam Milk",
    description: "Chilled, highly nourishing drink made of milk, almond paste, saffron strands, and crushed pistachios.",
    price: 220.0,
    category: "Beverages",
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1626132647523-66f5bf380027?w=800&q=80",
  },
  {
    name: "Jaljeera",
    description: "Zesty, traditional Indian summer drink made with roasted cumin, fresh mint, lime juice, and black salt.",
    price: 100.0,
    category: "Beverages",
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&q=80",
  },
  {
    name: "Chocolate Shake",
    description: "Chilled, thick, and delicious milkshake blended with cocoa powder, fresh milk, and chocolate ice cream.",
    price: 240.0,
    category: "Beverages",
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=800&q=80",
  },

  // 2. Starters
  {
    name: "Paneer Tikka",
    description: "Marinated cottage cheese cubes grilled with bell peppers and onions in a traditional clay oven.",
    price: 280.0,
    category: "Starters",
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800&q=80",
  },
  {
    name: "Chicken Tikka",
    description: "Boneless chicken chunks marinated in spiced tandoori yogurt and grilled to smoky perfection.",
    price: 340.0,
    category: "Starters",
    isVeg: false,
    imageUrl: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&q=80",
  },
  {
    name: "Hara Bhara Kebab",
    description: "Crispy pan-fried patties made of spinach, green peas, cottage cheese, and aromatic spices.",
    price: 240.0,
    category: "Starters",
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1626132647523-66f5bf380027?w=800&q=80",
  },
  {
    name: "Fish Amritsari",
    description: "Crispy batter-fried fish fillets seasoned with carom seeds, fresh lime, and warm Punjabi spices.",
    price: 420.0,
    category: "Starters",
    isVeg: false,
    imageUrl: "https://images.unsplash.com/photo-1624462966581-bc6d768cbce5?w=800&q=80",
  },
  {
    name: "Veg Manchurian",
    description: "Golden fried mixed vegetable balls tossed in a tangy, sweet, and spicy Indo-Chinese sauce.",
    price: 220.0,
    category: "Starters",
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&q=80",
  },
  {
    name: "Chicken 65",
    description: "Fiery, deep-fried chicken cubes tempered with curry leaves, cracked mustard seeds, and yogurt.",
    price: 320.0,
    category: "Starters",
    isVeg: false,
    imageUrl: "https://images.unsplash.com/photo-1610057099443-fde8c4d90ef8?w=800&q=80",
  },
  {
    name: "Aloo Tikki",
    description: "Crispy spiced potato patties served with sweet mint chutney, tangy tamarind, and spiced yogurt.",
    price: 160.0,
    category: "Starters",
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&q=80",
  },
  {
    name: "Mutton Seekh Kebab",
    description: "Skewered minced mutton blended with fresh ginger, garlic, and special tandoori spices, grilled over live charcoal.",
    price: 450.0,
    category: "Starters",
    isVeg: false,
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80",
  },

  // 3. Main Course
  {
    name: "Butter Chicken",
    description: "Tender tandoori chicken cooked in a rich, buttery, and highly aromatic tomato-cream gravy.",
    price: 420.0,
    category: "Main Course",
    isVeg: false,
    imageUrl: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800&q=80",
  },
  {
    name: "Paneer Butter Masala",
    description: "Rich and creamy dish made of cottage cheese cubes simmered in a mildly sweet, velvety tomato-onion gravy.",
    price: 340.0,
    category: "Main Course",
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=800&q=80",
  },
  {
    name: "Chicken Biryani",
    description: "Fragrant basmati rice layered with juicy tandoori chicken, saffron, and fresh mint, slow-cooked on dum.",
    price: 380.0,
    category: "Main Course",
    isVeg: false,
    imageUrl: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=800&q=80",
  },
  {
    name: "Dal Makhani",
    description: "Slow-cooked black lentils and kidney beans simmered overnight with fresh butter, cream, and warm spices.",
    price: 280.0,
    category: "Main Course",
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&q=80",
  },
  {
    name: "Mutton Rogan Josh",
    description: "Aromatic Kashmiri mutton dish slow-cooked with yogurt, ginger, garlic, and special mild red chilies.",
    price: 580.0,
    category: "Main Course",
    isVeg: false,
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80",
  },
  {
    name: "Palak Paneer",
    description: "Traditional North Indian cottage cheese cubes cooked in a rich, creamy, and healthy spiced spinach gravy.",
    price: 320.0,
    category: "Main Course",
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=800&q=80",
  },
  {
    name: "Fish Curry",
    description: "Tender fish steaks simmered in a highly tangy, spiced coconut-based authentic coastal gravy.",
    price: 480.0,
    category: "Main Course",
    isVeg: false,
    imageUrl: "https://images.unsplash.com/photo-1624462966581-bc6d768cbce5?w=800&q=80",
  },
  {
    name: "Veg Biryani",
    description: "Aromatic long-grain basmati rice cooked with perfectly layered fresh vegetables, saffron, and mint.",
    price: 300.0,
    category: "Main Course",
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&q=80",
  },

  // 4. Roties & Extras
  {
    name: "Butter Naan",
    description: "Soft, leavened clay-oven flatbread brushed with premium melted butter.",
    price: 70.0,
    category: "Roties & Extras",
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=800&q=80",
  },
  {
    name: "Tandoori Roti",
    description: "Traditional whole wheat flatbread baked on the hot clay walls of the tandoor.",
    price: 40.0,
    category: "Roties & Extras",
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=800&q=80",
  },
  {
    name: "Plain Roti",
    description: "Simple whole wheat round flatbread, roasted on a hot iron tawa without butter.",
    price: 25.0,
    category: "Roties & Extras",
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=800&q=80",
  },
  {
    name: "Jeera Rice",
    description: "Fragrant long-grain basmati rice tempered with roasted cumin seeds and fresh ghee.",
    price: 180.0,
    category: "Roties & Extras",
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&q=80",
  },
  {
    name: "Plain Rice",
    description: "Steamed fluffy aromatic basmati rice, a perfect side companion for mains and curries.",
    price: 140.0,
    category: "Roties & Extras",
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&q=80",
  },
  {
    name: "Garlic Naan",
    description: "Crispy tandoori naan flatbread seasoned with roasted minced garlic and fresh cilantro.",
    price: 90.0,
    category: "Roties & Extras",
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=800&q=80",
  },
  {
    name: "Lachha Paratha",
    description: "Multi-layered flaky whole wheat flatbread made with soft folds and roasted with ghee.",
    price: 80.0,
    category: "Roties & Extras",
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=800&q=80",
  },
  {
    name: "Masala Papad",
    description: "Crispy fried lentil cracker topped with tangy chopped onions, tomatoes, green chilies, and chaat masala.",
    price: 60.0,
    category: "Roties & Extras",
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&q=80",
  },

  // 5. Desserts
  {
    name: "Gulab Jamun",
    description: "Soft, golden berry-sized milk solids, deep-fried and soaked in a warm cardamom sugar syrup.",
    price: 120.0,
    category: "Desserts",
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&q=80",
  },
  {
    name: "Rasgulla",
    description: "Spongy, delicate, and feather-light paneer dumplings cooked in a sweet light sugar syrup.",
    price: 140.0,
    category: "Desserts",
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&q=80",
  },
  {
    name: "Jalebi",
    description: "Crispy, spiral-shaped deep-fried batter soaked overnight in rich saffron syrup, best served hot.",
    price: 150.0,
    category: "Desserts",
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&q=80",
  },
  {
    name: "Caramel Custard",
    description: "A classic egg-based, rich, and silky smooth vanilla custard baked over a sweet amber caramel glaze.",
    price: 220.0,
    category: "Desserts",
    isVeg: false,
    imageUrl: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80",
  },
  {
    name: "Kulfi",
    description: "Traditional, dense Indian ice cream flavored rich with saffron, green pistachios, and almond slivers.",
    price: 160.0,
    category: "Desserts",
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800&q=80",
  },
  {
    name: "Rasmalai",
    description: "Soft, spongy cottage cheese discs soaked in sweetened, cardamom-thickened milk, topped with pistachios.",
    price: 180.0,
    category: "Desserts",
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&q=80",
  },
  {
    name: "Chocolate Mousse",
    description: "Light, airy, and velvety dark chocolate mousse made with premium cocoa and organic egg whites.",
    price: 260.0,
    category: "Desserts",
    isVeg: false,
    imageUrl: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800&q=80",
  },
  {
    name: "Gajar Ka Halwa",
    description: "Traditional warm carrot pudding slow-cooked with ghee, milk solids (khoya), and loaded with dry fruits.",
    price: 190.0,
    category: "Desserts",
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&q=80",
  },
];

export async function seedProducts() {
  const count = await Product.countDocuments();
  if (count === 0) {
    await Product.insertMany(menu);
    console.log("Database seeded successfully with the updated 40-item Indian Food Menu!");
  } else {
    console.log("Database already has products, skipping seeding.");
  }
}
